services:
  app:
    build: ./app
    restart: unless-stopped
    ports:
      - "8001:8000"
    volumes:
      - /Volumes/MacSSD-4TB_Libraries/libraries/docbrowser_library/config.yaml:/app/config.yaml:ro
      - /Volumes/MacSSD-4TB_Libraries/libraries/docbrowser_library:/data/db
      - /Volumes/raydesktop:/data/docs:ro
    environment:
      - TZ=Asia/Tokyo
