services:
  app:
    container_name: docbrowser
    build: ./app
    restart: unless-stopped
    expose:
      - "8000"
    volumes:
      - /Volumes/MacSSD-4TB_Libraries/libraries/docbrowser_library/config.yaml:/app/config.yaml:ro
      - /Volumes/MacSSD-4TB_Libraries/libraries/docbrowser_library:/data/db
      - /Volumes/raydesktop/History/3_Life/2020-03-00_就活/0_ES:/data/docs:ro
    environment:
      - TZ=Asia/Tokyo

networks:
  default:
    external: true
    name: npm
